name: plinth
description: A local music player that preserves your folder structure.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.40
  just_audio_background: ^0.0.1-beta.12
  audio_service: ^0.18.12
  audio_session: ^0.1.21
  file_picker: ^8.1.2
  audio_metadata_reader: ^1.1.0
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  path: ^1.9.1
  path_provider: ^2.1.5
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: 0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/plinth_icon.png"
  adaptive_icon_background: "#0D0D0D"
  adaptive_icon_foreground: "assets/icon/plinth_icon.png"
